[workspace]
authors = ["Yoav Ram <yoavram@tauex.tau.ac.il>"]
channels = ["conda-forge"]
name = "modelspopbiol"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
marimo = "marimo edit . --watch --mcp --no-token"
marimo-check = "marimo check"
lektor = "cd www && lektor serve"

[dependencies]
python = "3.11.*"
numpy = "*"
pandas = "*"
matplotlib = "*"
seaborn = "*"
scipy = "*"
sympy = "*"
numba = ">=0.63.1,<0.64"
pyzmq = ">=27.1.0,<28"
emcee = ">=3.1.6,<4"
marimo = ">=0.23.9,<0.24"

[pypi-dependencies]
marimo = ">=0.23.3"
pydantic-ai = ">=0.2.4, <0.3"
corner = ">=2.2.3,<3"
altair = ">=6.0.0,<7"
mcp = ">=1.26.0,<2"
pymc = ">=5.28.5, <6"
preliz = ">=0.24.0, <0.25"
arviz = ">=0.23.4, <0.24"
arviz-base = ">=0.8.0, <0.9"
scikit-learn = ">=1.9.0, <2"
bambi = ">=0.17.2, <0.18"
rpy2 = ">=3.6.7, <4"
jax = ">=0.4.38, <0.11"
optax = ">=0.2.5, <0.3"
